#!/usr/bin/env bash
# =============================================================================
# ui-control-manifest.sh — regenerate / verify the UI-control coverage manifest.
#
# Cross-references literal/static-prefix data-testids on interactive UI elements
# with harness case actions/DOM assertions and uiDriver's named DOM actions.
# Default: replace the generated block in ui-control-manifest.md.  --check:
# render without writing, then diff it against the committed block.
#
# Plain bash + awk + sort only: macOS ships bash 3.2 and BWK awk.
# =============================================================================
set -euo pipefail

case "${1:-}" in
  "" ) check=0 ;;
  --check ) check=1 ;;
  * ) echo "usage: bash scripts/ui-control-manifest.sh [--check]" >&2; exit 2 ;;
esac

cd "$(dirname "$0")/.."

manifest=".claude/skills/e2e-loop/references/ui-control-manifest.md"
begin='<!-- BEGIN UI-CONTROL-MANIFEST: generated by scripts/ui-control-manifest.sh -->'
end_marker='<!-- END UI-CONTROL-MANIFEST -->'

if [ ! -f "$manifest" ]; then
  echo "ERROR: manifest missing: $manifest" >&2
  exit 1
fi
if [ "$(grep -Fxc "$begin" "$manifest" || true)" -ne 1 ] || [ "$(grep -Fxc "$end_marker" "$manifest" || true)" -ne 1 ]; then
  echo "ERROR: $manifest must contain exactly one BEGIN and one END marker" >&2
  exit 1
fi

tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/ui-control-manifest.XXXXXX")"
trap 'rm -rf "$tmpdir"' EXIT

# Stage A: source controls. A source testid belongs to the manifest when it is
# literal (or a static dynamic-family prefix) and its +/-3-line JSX window has
# an interactive element, interactive role, or event handler. This deliberately
# excludes static display-only ids and opaque computed ids with no stable key.
awk '
function flushfile(    i,line,s,testid,kind,lo,hi,w,interactive,wl) {
  if (n == 0) return
  for (i = 1; i <= n; i++) {
    line = lines[i]; testid = ""; kind = ""
    if (match(line, /data-testid="[A-Za-z0-9_-]+"/)) {
      s = substr(line, RSTART, RLENGTH); testid = s
      sub(/^data-testid="/, "", testid); sub(/"$/, "", testid); kind = "exact"
    } else if (match(line, /data-testid=\{`[A-Za-z0-9_-]*\$\{/)) {
      s = substr(line, RSTART, RLENGTH); testid = s
      sub(/^data-testid=\{`/, "", testid); sub(/\$\{$/, "", testid); kind = "prefix"
    } else continue
    if (testid == "") continue
    lo = i - 3; if (lo < 1) lo = 1
    hi = i + 3; if (hi > n) hi = n
    interactive = 0
    for (w = lo; w <= hi; w++) {
      wl = lines[w]
      if (wl ~ /<(button|select|input|textarea|a )/ || wl ~ /onClick=|onChange=|onSubmit=|onKeyDown=|onPointerDown=/ || wl ~ /role="(button|tab|switch|menuitem|link|option)"/) {
        interactive = 1; break
      }
    }
    if (interactive) print testid "\t" kind
  }
}
FNR == 1 { flushfile(); n = 0; delete lines }
{ lines[++n] = $0 }
END { flushfile() }
' apps/ui/src/**/*.tsx apps/ui/src/*.tsx 2>/dev/null | LC_ALL=C sort -u > "$tmpdir/controls.tsv"

# Stage B: case-authored UI actions are interactions; DOM anchors and navigation
# settle targets are read-only checks. Whole ids remain whole ids; a prefix is
# honored only when the case explicitly declares match="prefix".
awk '
function quoted(s) { if (match(s, /"[^"]*"/)) return substr(s, RSTART + 1, RLENGTH - 2); return "" }
function flush() {
  if (hdr == "steps.ui_actions" && testid != "") {
    if (verb == "click" || verb == "fill" || verb == "select" || verb == "press" || verb == "drag") print testid "\tINTERACTED\texact"
    else if (verb == "navigate") print testid "\tREAD_ONLY\texact"
  } else if (hdr == "steps.anchors" && kind == "dom_state" && testid != "") {
    print testid "\tREAD_ONLY\t" (matchkind == "" ? "exact" : matchkind)
  }
  verb = ""; testid = ""; kind = ""; matchkind = ""
}
/^[ \t]*\[\[/ { flush(); h = $0; gsub(/^[ \t]*\[\[[ \t]*/, "", h); gsub(/[ \t]*\]\][ \t]*$/, "", h); hdr = h; next }
/^[ \t]*\[[^\[]/ { flush(); hdr = ""; next }
/^[ \t]*verb[ \t]*=/ { verb = quoted($0) }
/^[ \t]*testid[ \t]*=/ { testid = quoted($0) }
/^[ \t]*kind[ \t]*=/ { kind = quoted($0) }
/^[ \t]*match[ \t]*=/ { matchkind = quoted($0) }
/^[ \t]*button_testid[ \t]*=/ { print quoted($0) "\tINTERACTED\texact" }
END { flush() }
' harness/cases/*.toml | LC_ALL=C sort -u > "$tmpdir/cases.tsv"

# Stage C: named uiDriver methods contain testids that a resume action reaches
# indirectly. Do not derive a prefix from a template with two variables: its
# first literal segment could falsely cover unrelated sibling controls.
awk '
{
  line = $0
  if (line !~ /tid\(|data-testid/) next
  testid = ""; kind = ""; multivar = (gsub(/\$\{/, "&", line) >= 2)
  if (match(line, /tid\("[A-Za-z0-9_-]+"\)/)) {
    testid = substr(line, RSTART, RLENGTH); sub(/^tid\("/, "", testid); sub(/"\)$/, "", testid); kind = "exact"
  } else if (!multivar && match(line, /tid\(`[A-Za-z0-9_-]*\$\{/)) {
    testid = substr(line, RSTART, RLENGTH); sub(/^tid\(`/, "", testid); sub(/\$\{$/, "", testid); kind = "prefix"
  } else if (!multivar && match(line, /data-testid\^="[A-Za-z0-9_-]+"/)) {
    testid = substr(line, RSTART, RLENGTH); sub(/^data-testid\^="/, "", testid); sub(/"$/, "", testid); kind = "prefix"
  } else if (match(line, /data-testid="[A-Za-z0-9_-]+"/)) {
    testid = substr(line, RSTART, RLENGTH); sub(/^data-testid="/, "", testid); sub(/"$/, "", testid); kind = "exact"
  }
  if (testid == "") next
  state = (line ~ /\.click\(|\.fill\(|\.selectOption\(|\.press\(|\.type\(|\.check\(|\.dragTo\(|\.tap\(/) ? "INTERACTED" : "READ_ONLY"
  print testid "\t" state "\t" kind
}
' harness/uiDriver.ts | LC_ALL=C sort -u > "$tmpdir/driver.tsv"

cat "$tmpdir/cases.tsv" "$tmpdir/driver.tsv" | LC_ALL=C sort -u > "$tmpdir/usage.tsv"

# Stage D: exact controls only match exact ids unless a usage explicitly says
# prefix. Dynamic families match a member or an overlapping family. INTERACTED
# wins over READ_ONLY, which wins over no usage.
awk -F '\t' '
function starts_with(s, p) { return substr(s, 1, length(p)) == p }
FNR == NR { n++; mtestid[n] = $1; mkind[n] = $2; next }
{ ucount++; utestid[ucount] = $1; ustate[ucount] = $2; umatch[ucount] = $3 }
END {
  for (i = 1; i <= n; i++) {
    best = "NEVER_TOUCHED"
    for (j = 1; j <= ucount; j++) {
      covered = 0
      if (mkind[i] == "exact" && umatch[j] == "exact") covered = (mtestid[i] == utestid[j])
      else if (mkind[i] == "exact" && umatch[j] == "prefix") covered = starts_with(mtestid[i], utestid[j])
      else if (mkind[i] == "prefix" && umatch[j] == "exact") covered = starts_with(utestid[j], mtestid[i])
      else covered = starts_with(mtestid[i], utestid[j]) || starts_with(utestid[j], mtestid[i])
      if (covered) {
        if (ustate[j] == "INTERACTED") { best = "INTERACTED"; break }
        if (ustate[j] == "READ_ONLY" && best != "INTERACTED") best = "READ_ONLY"
      }
    }
    print mtestid[i] "\t" mkind[i] "\t" best
  }
}
' "$tmpdir/controls.tsv" "$tmpdir/usage.tsv" > "$tmpdir/classified.tsv"

{
  printf '%s\n' "$begin"
  printf '| testid | key kind | coverage |\n'
  printf '| --- | --- | --- |\n'
  awk -F '\t' '{ state = ($3 == "INTERACTED" ? "interacted" : ($3 == "READ_ONLY" ? "read-only-checked" : "never-touched")); printf "| `%s` | %s | %s |\n", $1, $2, state }' "$tmpdir/classified.tsv"
  printf '%s\n' "$end_marker"
} > "$tmpdir/block.md"

awk -v begin="$begin" -v end_marker="$end_marker" -v block="$tmpdir/block.md" '
  $0 == begin {
    while ((getline line < block) > 0) print line
    close(block); inside = 1; next
  }
  $0 == end_marker { inside = 0; next }
  !inside { print }
' "$manifest" > "$tmpdir/rendered.md"

if [ "$check" -eq 1 ]; then
  if diff -u "$manifest" "$tmpdir/rendered.md"; then
    echo "OK: UI-control manifest is current."
  else
    echo "ERROR: UI-control manifest is stale; run bash scripts/ui-control-manifest.sh" >&2
    exit 1
  fi
else
  mv "$tmpdir/rendered.md" "$manifest"
  echo "Updated $manifest"
fi
